//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEBGroup.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerInfo
    {
        public int companyID { get; set; }
        public string company { get; set; }
        public string contactPerson { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public string e_mail { get; set; }
    }
}
