//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEBGroup.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EAL39_DBEntities : DbContext
    {
        public EAL39_DBEntities()
            : base("name=EAL39_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<customerInfo> customerInfo { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<room> room { get; set; }
        public virtual DbSet<SCPconnection> SCPconnection { get; set; }
        public virtual DbSet<sector> sector { get; set; }
    }
}
