//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEBGroup.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCPconnection
    {
        public int scpconnectionID { get; set; }
        public Nullable<int> sectorID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> productID { get; set; }
    
        public virtual category category { get; set; }
        public virtual product product { get; set; }
        public virtual sector sector { get; set; }
    }
}
